apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: studentsphere
type: Opaque
stringData:
  DB_NAME: student_db
  DB_USER: student
  DB_PASS: student123
  DB_URL: jdbc:mariadb://mariadb-service:3306/student_db
